// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.27.3
// source: proto/bigquery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepDelay      int64                  `protobuf:"varint,1,opt,name=dep_delay,json=depDelay,proto3" json:"dep_delay,omitempty"`
	ArrDelay      int64                  `protobuf:"varint,2,opt,name=arr_delay,json=arrDelay,proto3" json:"arr_delay,omitempty"`
	AirTime       int64                  `protobuf:"varint,3,opt,name=air_time,json=airTime,proto3" json:"air_time,omitempty"`
	Distance      int64                  `protobuf:"varint,4,opt,name=distance,proto3" json:"distance,omitempty"`
	DepTime       float64                `protobuf:"fixed64,5,opt,name=dep_time,json=depTime,proto3" json:"dep_time,omitempty"`
	ArrTime       float64                `protobuf:"fixed64,6,opt,name=arr_time,json=arrTime,proto3" json:"arr_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_bigquery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bigquery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_bigquery_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetDepDelay() int64 {
	if x != nil {
		return x.DepDelay
	}
	return 0
}

func (x *Row) GetArrDelay() int64 {
	if x != nil {
		return x.ArrDelay
	}
	return 0
}

func (x *Row) GetAirTime() int64 {
	if x != nil {
		return x.AirTime
	}
	return 0
}

func (x *Row) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Row) GetDepTime() float64 {
	if x != nil {
		return x.DepTime
	}
	return 0
}

func (x *Row) GetArrTime() float64 {
	if x != nil {
		return x.ArrTime
	}
	return 0
}

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_bigquery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bigquery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_bigquery_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_proto_bigquery_proto protoreflect.FileDescriptor

var file_proto_bigquery_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x67, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x70, 0x62, 0x22,
	0xac, 0x01, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x5f, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x70, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x72, 0x5f, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x72, 0x72, 0x44, 0x65, 0x6c, 0x61,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x69, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x69, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x70, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x64, 0x65, 0x70, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x61, 0x72, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x29,
	0x0a, 0x05, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x70, 0x62, 0x2e,
	0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x46, 0x4d, 0x56, 0x2f, 0x62, 0x69, 0x67,
	0x70, 0x67, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_proto_bigquery_proto_rawDescOnce sync.Once
	file_proto_bigquery_proto_rawDescData []byte
)

func file_proto_bigquery_proto_rawDescGZIP() []byte {
	file_proto_bigquery_proto_rawDescOnce.Do(func() {
		file_proto_bigquery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bigquery_proto_rawDesc), len(file_proto_bigquery_proto_rawDesc)))
	})
	return file_proto_bigquery_proto_rawDescData
}

var file_proto_bigquery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bigquery_proto_goTypes = []any{
	(*Row)(nil),   // 0: arrowpb.Row
	(*Batch)(nil), // 1: arrowpb.Batch
}
var file_proto_bigquery_proto_depIdxs = []int32{
	0, // 0: arrowpb.Batch.rows:type_name -> arrowpb.Row
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bigquery_proto_init() }
func file_proto_bigquery_proto_init() {
	if File_proto_bigquery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bigquery_proto_rawDesc), len(file_proto_bigquery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bigquery_proto_goTypes,
		DependencyIndexes: file_proto_bigquery_proto_depIdxs,
		MessageInfos:      file_proto_bigquery_proto_msgTypes,
	}.Build()
	File_proto_bigquery_proto = out.File
	file_proto_bigquery_proto_goTypes = nil
	file_proto_bigquery_proto_depIdxs = nil
}
